# Generated by Django 5.2.12 on 2026-04-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measurement', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('arrival ', 'Приход'), ('expense', 'Расход')], default='arrival ')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=220)),
                ('show', models.BooleanField(default=True)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.measurement')),
                ('tariff', models.ManyToManyField(to='settings.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('considered', 'Враховане'), ('no_considered', 'Не враховане')], default='new')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
            ],
        ),
        migrations.CreateModel(
            name='Tarrif_Service_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='no_conducted', verbose_name=[('no_conducted', 'Не проведена'), ('conducted', 'Проведена')])),
                ('amount', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField()),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cash_register')),
                ('service', models.ManyToManyField(to='settings.service')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('no_paid', 'Не оплачено'), ('partially', 'Частично'), ('paid', 'Оплачено')], default='no_paid')),
                ('comment', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.transaction')),
            ],
        ),
    ]
