# Generated by Django 5.2.12 on 2026-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='special_id',
            field=models.CharField(default=None, max_length=220, unique=True),
            preserve_default=False,
        ),
    ]
