# Generated by Django 5.2.12 on 2026-04-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='measurement',
        ),
    ]
