# Generated by Django 5.2.12 on 2026-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_counters_special_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
    ]
