# Generated by Django 5.2.12 on 2026-04-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_service_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.measurement'),
        ),
    ]
