# Generated by Django 5.2.12 on 2026-05-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
        ('settings', '0003_counters_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counters',
            name='account',
        ),
        migrations.AddField(
            model_name='counters',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counters',
            name='create_time',
            field=models.DateField(),
        ),
    ]
