# Generated by Django 5.2.12 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_service_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
