# Generated by Django 5.2.12 on 2026-05-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_counters_account_counters_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cash_register',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
