# Generated by Django 5.2.12 on 2026-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_tariff_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
