# Generated by Django 5.2.12 on 2026-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(unique=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('arrival ', 'Приход'), ('expense', 'Расход')])),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_unique_id', models.IntegerField(unique=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('no_paid', 'Не оплачено'), ('partially', 'Частично'), ('paid', 'Оплачено')], default='no_paid')),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_book', models.CharField(max_length=220, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')])),
            ],
        ),
        migrations.CreateModel(
            name='ThoughInvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicator', models.CharField(max_length=20)),
                ('measurement_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='conducted', verbose_name=[('conducted', 'Проведена'), ('no_conducted', 'Не проведена')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
