# Generated by Django 5.2.12 on 2026-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('arrival ', 'Приход'), ('expense', 'Расход')])),
                ('sum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('no_paid', 'Не оплачено'), ('partially', 'Частично'), ('paid', 'Оплачено')], default='no_paid')),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_book', models.CharField(max_length=220, unique=True)),
                ('balance', models.CharField(default=0, max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='no_conducted', verbose_name=[('no_conducted', 'Не проведена'), ('conducted', 'Проведена')])),
                ('amount', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
