# Generated by Django 5.2.12 on 2026-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('arrival ', 'Приход'), ('expense', 'Расход')])),
                ('sum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_book', models.CharField(max_length=220, unique=True)),
                ('balance', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
