# Generated by Django 5.2.12 on 2026-05-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('houses', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service'),
        ),
        migrations.AddField(
            model_name='payment_account',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account'),
        ),
        migrations.AddField(
            model_name='cash_register',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cash_register'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ManyToManyField(to='settings.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
        ),
    ]
