# Generated by Django 5.2.12 on 2026-05-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('houses', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_register',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tariff'),
        ),
        migrations.AddField(
            model_name='payment_account',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account'),
        ),
        migrations.AddField(
            model_name='cash_register',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account'),
        ),
        migrations.AddField(
            model_name='thoughinvoiceservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='thoughinvoiceservice',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.measurement'),
        ),
        migrations.AddField(
            model_name='thoughinvoiceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ManyToManyField(through='finance.ThoughInvoiceService', to='settings.service'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.cash_register'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
    ]
