# Generated by Django 5.2.12 on 2026-04-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_account',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
        ),
        migrations.AddField(
            model_name='cash_register',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account'),
        ),
    ]
