# Generated by Django 5.2.12 on 2026-05-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('no_conducted', 'Не проведена'), ('conducted', 'Проведена')], default='no_conducted'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='create_time',
            field=models.DateField(),
        ),
    ]
