# Generated by Django 5.2.12 on 2026-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_register',
            name='article',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
