# Generated by Django 5.2.12 on 2026-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_account',
            name='balance',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment_account',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
