# Generated by Django 5.2.12 on 2026-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_period_end_invoice_period_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_unique_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
