# Generated by Django 5.2.12 on 2026-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cash_register_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_register',
            name='status',
            field=models.CharField(choices=[('conducted', 'Проведена'), ('no_conducted', 'Не проведена')], default='conducted'),
            preserve_default=False,
        ),
    ]
