# Generated by Django 5.2.12 on 2026-05-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoice_invoice_unique_id'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settings.tariff'),
            preserve_default=False,
        ),
    ]
