# Generated by Django 5.2.12 on 2026-05-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payment_account_balance_and_more'),
        ('settings', '0005_remove_transaction_cash_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='no_conducted', verbose_name=[('no_conducted', 'Не проведена'), ('conducted', 'Проведена')])),
                ('amount', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField()),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cash_register')),
                ('service', models.ManyToManyField(to='settings.service')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('no_paid', 'Не оплачено'), ('partially', 'Частично'), ('paid', 'Оплачено')], default='no_paid')),
                ('comment', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
        ),
    ]
