# Generated by Django 5.2.12 on 2026-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_invoice_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(choices=[('no_conducted', 'Не проведена'), ('conducted', 'Проведена')], default='no_conducted'),
        ),
    ]
