# Generated by Django 5.2.12 on 2026-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cash_register_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_register',
            name='status',
            field=models.BooleanField(),
        ),
    ]
