# Generated by Django 5.2.12 on 2026-05-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoice_status'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(choices=[('conducted', 'Проведена'), ('no_conducted', 'Не проведена')], default='conducted'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='conducted', verbose_name=[('conducted', 'Проведена'), ('no_conducted', 'Не проведена')]),
        ),
        migrations.CreateModel(
            name='ThoughInvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicator', models.CharField(max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ManyToManyField(through='finance.ThoughInvoiceService', to='settings.service'),
        ),
    ]
