# Generated by Django 5.2.12 on 2026-06-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_cash_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_register',
            name='create_time',
            field=models.DateField(),
        ),
    ]
