# Generated by Django 5.2.12 on 2026-05-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_invoice_service_alter_invoice_status_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughinvoiceservice',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.measurement'),
        ),
        migrations.AddField(
            model_name='thoughinvoiceservice',
            name='measurement_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('conducted', 'Проведена'), ('no_conducted', 'Не проведена')], default='conducted'),
        ),
    ]
