# Generated by Django 5.2.12 on 2026-06-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_cash_register_create_time'),
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_account',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='houses.apartment'),
        ),
    ]
