# Generated by Django 5.2.12 on 2026-06-04 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_payment_account_apartment'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cash_register',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(unique=True)),
                ('create_time', models.DateField()),
                ('type', models.CharField(choices=[('arrival ', 'Приход'), ('expense', 'Расход')])),
                ('status', models.BooleanField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payment_account')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings.transactionpurpose')),
                ('manager', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cash_Register',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
