# Generated by Django 5.2.12 on 2026-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_thoughinvoiceservice_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
