# Generated by Django 5.2.12 on 2026-06-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_cashregister_manager'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.transactionpurpose'),
        ),
    ]
