# Generated by Django 5.2.12 on 2026-05-11 19:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, choices=[('ru', 'ru'), ('uk', 'uk'), ('eng', 'eng')], default='uk', max_length=4, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\+380\\d{9}$')])),
                ('viber', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\+380\\d{9}$')])),
                ('telegram', models.CharField(blank=True, max_length=225, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_status', models.CharField(choices=[('active', 'Активен'), ('new', 'Новий'), ('inactive', 'Отключен')], default='new')),
                ('user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_main_image', to='common.image')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=225)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('accountant', 'Бухгалтер'), ('electrician', 'Електрик'), ('plumber', 'Сантехник')], default='uk', max_length=40)),
                ('statistics', models.BooleanField(default=False)),
                ('transaction', models.BooleanField(default=False)),
                ('receipts', models.BooleanField(default=False)),
                ('payment_account', models.BooleanField(default=False)),
                ('apartments_owner', models.BooleanField(default=False)),
                ('apartments', models.BooleanField(default=False)),
                ('house', models.BooleanField(default=False)),
                ('messages', models.BooleanField(default=False)),
                ('call_master', models.BooleanField(default=False)),
                ('counters', models.BooleanField(default=False)),
                ('site_control', models.BooleanField(default=False)),
                ('services', models.BooleanField(default=False)),
                ('tariff', models.BooleanField(default=False)),
                ('role_list', models.BooleanField(default=False)),
                ('users', models.BooleanField(default=False)),
                ('payment_data', models.BooleanField(default=False)),
                ('transaction_propose', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(limit_choices_to={'is_admin': True}, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
