# Generated by Django 5.2.12 on 2026-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='apartments_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='payment_data',
            field=models.BooleanField(default=False),
        ),
    ]
