# Generated by Django 5.2.12 on 2026-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'ru'), ('uk', 'uk'), ('eng', 'eng')], default='uk', max_length=4, null=True),
        ),
    ]
