# Generated by Django 5.2.12 on 2026-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_apartments_owner_role_payment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='transaction_propose',
            field=models.BooleanField(default=False),
        ),
    ]
