# Generated by Django 5.2.12 on 2026-04-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_sender_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
