# Generated by Django 5.2.12 on 2026-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_master',
            name='data_create',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call_master',
            name='сonvenient_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
