# Generated by Django 5.2.12 on 2026-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_call_master_data_create_call_master_сonvenient_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_master',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('manager', 'Менеджер'), ('electrician', 'Електрик'), ('plumber', 'Сантехник')], default=None),
            preserve_default=False,
        ),
    ]
