# Generated by Django 5.2.12 on 2026-04-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.TextField()),
                ('image_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_1', to='common.image')),
                ('image_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_2', to='common.image')),
                ('image_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_3', to='common.image')),
                ('image_4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_4', to='common.image')),
                ('image_5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_5', to='common.image')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('section_number', models.CharField(max_length=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('section_number', models.CharField(max_length=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section')),
                ('storey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.storey')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
    ]
