# Generated by Django 5.2.12 on 2026-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=10)),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Call_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateField()),
                ('сonvenient_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('accountant', 'Бухгалтер'), ('electrician', 'Електрик'), ('plumber', 'Сантехник')])),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В роботі'), ('completed', 'Виконано')], default='new')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('section_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('section_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=220)),
            ],
        ),
    ]
