# Generated by Django 5.2.12 on 2026-04-29 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call_master',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
        ),
        migrations.AddField(
            model_name='call_master',
            name='master',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call_master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='image_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_1', to='common.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_2', to='common.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_3', to='common.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_4', to='common.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_image_5', to='common.image'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AddField(
            model_name='storey',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='storey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.storey'),
        ),
        migrations.AddField(
            model_name='worker',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
