# Generated by Django 5.2.12 on 2026-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
