# Generated by Django 5.2.12 on 2026-04-21 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateField()),
                ('сonvenient_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('accountant', 'Бухгалтер'), ('electrician', 'Електрик'), ('plumber', 'Сантехник')])),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В роботі'), ('completed', 'Виконано')], default='new')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment')),
                ('master', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
