# Generated by Django 5.2.12 on 2026-04-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=20)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='')),
                ('image_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_image_1', to='common.image')),
                ('image_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_image_2', to='common.image')),
                ('image_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_image_3', to='common.image')),
                ('manager_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_manager', to='common.image')),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=20)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('coordinate', models.TextField()),
                ('full_name', models.CharField(max_length=220)),
                ('location', models.TextField()),
                ('adress', models.TextField()),
                ('email_adress', models.EmailField(max_length=254)),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Main_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=20)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('main', 'main'), ('service', 'service')], default='main', max_length=10)),
                ('image_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image_1', to='common.image')),
                ('image_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image_2', to='common.image')),
                ('image_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image_3', to='common.image')),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_name', models.CharField(max_length=20)),
                ('additional_description', models.TextField()),
                ('about_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_control.about_page')),
                ('additional_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('main_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_control.main_page')),
            ],
        ),
    ]
