# Generated by Django 5.2.12 on 2026-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('site_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_page',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='about_page',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='about_page',
            name='image_1',
        ),
        migrations.AddField(
            model_name='about_page',
            name='image_1',
            field=models.ManyToManyField(related_name='about_image', to='common.image'),
        ),
    ]
