# Generated by Django 5.2.12 on 2026-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_control', '0002_remove_about_page_image_2_remove_about_page_image_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_page',
            old_name='image_1',
            new_name='image',
        ),
    ]
