# Generated by Django 5.2.12 on 2026-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_control', '0003_rename_image_1_about_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_page',
            name='show_app',
            field=models.BooleanField(default=True),
        ),
    ]
